### ISSUE TITLE
Comments in tsconfig break the linter

### ISSUE THREAD

**Issue by AbleLincoln** [vitonsky/eslint-plugin-paths#37]

**Comment by vitonsky** [comment]
What's name of file for config you use? I use `tsconfig.json` in my projects and i never used comments in this file, because json format does not support comments as i know

**Comment by AbleLincoln** [comment]
I am also using a `.json` file. I am pretty confused as to how the comments
are being allowed in the file. The project is a generated T3 app
<https://create.t3.gg/>, so I didn't make the tsconfig. It looks like the
Typescript compiler actually allows comments
<https://www.reddit.com/r/typescript/comments/8na5vb/tsconfigjson_isnt_strict_json_what_now/>
in its config file, so perhaps it is worth supporting in your plugin?

**Comment by AbleLincoln** [comment]
I am also using a `.json` file. I am pretty confused as to how the comments are being allowed in the file. The project is a generated [T3 app](https://create.t3.gg/), so I didn't make the tsconfig. It looks like the Typescript compiler actually [allows comments](https://www.reddit.com/r/typescript/comments/8na5vb/tsconfigjson_isnt_strict_json_what_now) in its config file. Perhaps it is worth supporting in the plugin?

**Comment by vitonsky** [comment]
> It looks like the Typescript compiler actually [allows comments](https://www.reddit.com/r/typescript/comments/8na5vb/tsconfigjson_isnt_strict_json_what_now) in its config file. Perhaps it is worth supporting in the plugin?

Sure, if tsconfig file supports comments, then current behavior is definitely are bug. I will fix it soon, thank you for report
