### ISSUE TITLE
[ENHANCEMENT]: export types

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [vitonsky/eslint-plugin-paths#56]
Hi, since the project is already in full typescript, it should be trivial to export the types (.d.ts file) with Rollup.

**Comment by vitonsky** [comment]
Hi, sure it is possible. Which use case we may solve with this change?

**Comment by AndreaPontrandolfo** [comment]
I'm importing your plugin in my sharable config and typescript complains that it cannot find the types declaration.
Of course i just "silence" it with `declare module 'eslint-plugin-paths';` but it would be better if it was types. 
It basically makes it easier to consume for users like me which want to use it inside their own libraries.

**Comment by vitonsky** [comment]
It make sense, i will implement it soon
